#include "vkbasalt_bridge.hpp"
#include <algorithm>
#include <filesystem>
#include <fstream>

namespace fs = std::filesystem;
namespace lsfg_android::vkbasalt {

static std::string quote(const std::string& s) {
    std::string out = "\"";
    for (char c : s) {
        if (c == '\\' || c == '"') out.push_back('\\');
        out.push_back(c);
    }
    out.push_back('"');
    return out;
}

bool writeConfig(const std::string& path, const Config& c) {
    std::ofstream out(path, std::ios::trunc);
    if (!out) return false;
    out << "# DeepDrop vkBasalt configuration generated by the app\n";
    out << "effects = ";
    for (size_t i = 0; i < c.effects.size(); ++i) {
        if (i) out << ':';
        out << c.effects[i];
    }
    out << "\n";
    // vkBasalt's ReShade bridge uses an effect-name -> .fx path mapping.
    // Built-in vkBasalt effect names are left untouched; user imported names
    // are resolved against the configured ReShade shader directory.
    for (const auto& effect : c.effects) {
        if (effect == "cas" || effect == "dls" || effect == "fxaa" ||
            effect == "smaa" || effect == "deband" || effect == "lut")
            continue;
        if (!c.reshadeIncludePath.empty())
            out << effect << " = " << quote(c.reshadeIncludePath + "/" + effect + ".fx") << "\n";
    }
    out << "reshadeTexturePath = " << quote(c.reshadeTexturePath) << "\n";
    out << "reshadeIncludePath = " << quote(c.reshadeIncludePath) << "\n";
    out << "depthCapture = " << (c.depthCapture ? "on" : "off") << "\n";
    out << "enableOnLaunch = " << (c.enableOnLaunch ? "True" : "False") << "\n";
    out << "casSharpness = " << c.casSharpness << "\n";
    out << "dlsSharpness = " << c.dlsSharpness << "\n";
    out << "dlsDenoise = " << c.dlsDenoise << "\n";
    out << "fxaaQualitySubpix = " << c.fxaaQualitySubpix << "\n";
    out << "fxaaQualityEdgeThreshold = " << c.fxaaQualityEdgeThreshold << "\n";
    out << "fxaaQualityEdgeThresholdMin = " << c.fxaaQualityEdgeThresholdMin << "\n";
    out << "smaaThreshold = " << c.smaaThreshold << "\n";
    out << "smaaMaxSearchSteps = " << c.smaaMaxSearchSteps << "\n";
    out << "smaaMaxSearchStepsDiag = " << c.smaaMaxSearchStepsDiag << "\n";
    out << "smaaCornerRounding = " << c.smaaCornerRounding << "\n";
    out << "lutFile = " << quote(c.lutFile) << "\n";
    return static_cast<bool>(out);
}

bool validateFxPath(const std::string& path) {
    std::error_code ec;
    return fs::is_regular_file(path, ec) &&
           fs::path(path).extension() == ".fx";
}

std::vector<std::string> scanFxDirectory(const std::string& directory) {
    std::vector<std::string> result;
    std::error_code ec;
    if (!fs::is_directory(directory, ec)) return result;
    for (const auto& e : fs::directory_iterator(directory, ec)) {
        if (ec) break;
        if (e.is_regular_file(ec) && e.path().extension() == ".fx")
            result.push_back(e.path().filename().string());
    }
    std::sort(result.begin(), result.end());
    return result;
}

} // namespace lsfg_android::vkbasalt
